2025-09-22 18:52:35 WARNING sirep.app.api [api.py:42]: Fuso horário 'America/Sao_Paulo' não encontrado; usando UTC como fallback
2025-09-22 18:52:49 INFO sirep.app.captura [captura.py:194]: captura iniciada
2025-09-22 18:53:44 INFO sirep.app.captura [captura.py:309]: captura finalizada: concluido
2025-09-22 19:07:02 WARNING sirep.app.api [api.py:42]: Fuso horário 'America/Sao_Paulo' não encontrado; usando UTC como fallback
2025-09-22 19:09:27 WARNING sirep.app.api [api.py:42]: Fuso horário 'America/Sao_Paulo' não encontrado; usando UTC como fallback
2025-09-22 19:19:42 WARNING sirep.app.api [api.py:42]: Fuso horário 'America/Sao_Paulo' não encontrado; usando UTC como fallback
2025-09-22 19:32:54 WARNING sirep.app.api [api.py:42]: Fuso horário 'America/Sao_Paulo' não encontrado; usando UTC como fallback
2025-09-22 19:43:12 WARNING sirep.app.api [api.py:42]: Fuso horário 'America/Sao_Paulo' não encontrado; usando UTC como fallback
2025-09-22 19:44:18 WARNING sirep.app.api [api.py:42]: Fuso horário 'America/Sao_Paulo' não encontrado; usando UTC como fallback
2025-09-22 20:16:26 WARNING sirep.app.api [api.py:42]: Fuso horário 'America/Sao_Paulo' não encontrado; usando UTC como fallback
2025-09-22 20:31:10 WARNING sirep.app.api [api.py:42]: Fuso horário 'America/Sao_Paulo' não encontrado; usando UTC como fallback
2025-09-22 20:39:54 INFO sirep.app.captura [captura.py:159]: captura iniciada
2025-09-22 20:40:51 INFO sirep.app.captura [captura.py:274]: captura finalizada: concluido
2025-09-22 20:46:55 WARNING sirep.app.api [api.py:42]: Fuso horário 'America/Sao_Paulo' não encontrado; usando UTC como fallback
2025-09-22 20:56:26 WARNING sirep.app.api [api.py:42]: Fuso horário 'America/Sao_Paulo' não encontrado; usando UTC como fallback
2025-09-22 21:08:59 WARNING sirep.app.api [api.py:58]: Fuso horário 'America/Sao_Paulo' não encontrado; usando UTC como fallback
2025-09-22 21:11:38 INFO sirep.app.captura [captura.py:159]: captura iniciada
2025-09-22 21:12:23 INFO sirep.app.captura [captura.py:192]: captura pausada
2025-09-22 21:12:28 INFO sirep.app.captura [captura.py:274]: captura finalizada: pausado
2025-09-22 21:12:35 WARNING sirep.app.api [api.py:58]: Fuso horário 'America/Sao_Paulo' não encontrado; usando UTC como fallback
2025-09-22 21:27:24 WARNING sirep.app.api [api.py:58]: Fuso horário 'America/Sao_Paulo' não encontrado; usando UTC como fallback
2025-09-22 21:28:03 INFO sirep.app.captura [captura.py:159]: captura iniciada
2025-09-22 21:28:59 INFO sirep.app.captura [captura.py:274]: captura finalizada: concluido
